### ISSUE TITLE
implement meta-diagram model and factories

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/meta-diagram#3]
- [x] implement MetaDiagram class
- [x] implement MetaLink class
- [x] implement CustomNodeModel
- [x] implement CustomLinkModel
- [x] Link the abstract node factory to meta-diagram
- [x] Link the abstract link factory to meta-diagram
- [x] dynamic population of the factories based on the componentsMap given in input
